languages: minimal

services:
  - docker

install:
  - docker pull jjmerelo/raku-test

script: docker run -t  --entrypoint="/bin/sh" -v  $TRAVIS_BUILD_DIR:/test jjmerelo/raku-test -c "apk add --update --no-cache libcmark && cp /usr/lib/libcmark.so.0.29.0 /usr/lib/libcmark.so && zef install --deps-only . && zef test ."
