language: perl6

os:
  - linux

perl6:
  - latest

install:
  - git clone https://github.com/commonmark/cmark.git
  - (cd cmark && make INSTALL_PREFIX=$HOME/cmark_bin && make install)
  - rakudobrew build zef
script:
  - LD_LIBRARY_PATH=$HOME/cmark_bin zef install .
  - PERL6LIB=$PWD/blib/lib LD_LIBRARY_PATH=$HOME/cmark_bin/lib/ prove -e perl6 -vr t/
